name: Build DEV version
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  #build-image-container:
  #  name: BUILD
  #  uses: Cloud-for-You/github-workflows/.github/workflows/build-generic-container.yaml@main
  #  secrets: inherit

  create-pr:
    name: Create PR to main
    #needs: build-image-container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}
      - name: Create Pull Request to main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head ${{ github.ref_name }} \
            --title "chore: sync from dev branch" \
            --body "Auto-created Pull Request"