name: Release and build application
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  build-image-container:
    uses: Cloud-for-You/github-workflows/.github/workflows/build-generic-container.yaml@main
    secrets: inherit